apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: chatapp
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://backend-service:8000;
        }
    }
